# Generated by Django 4.1.2 on 2022-10-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vote_justification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='justification',
        ),
    ]
