# Generated by Django 4.1.2 on 2022-10-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_vote_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='justification',
            field=models.CharField(default='', max_length=500),
        ),
    ]
