# Generated by Django 4.1.2 on 2022-11-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_user_name"),
        ("api", "0007_remove_vote_unique question-user_and_more"),
    ]

    operations = []
