# Generated by Django 4.1.2 on 2022-11-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_tag_question_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(
                choices=[
                    ("PM", "PM"),
                    ("REQ", "REQ"),
                    ("A&D", "A&D"),
                    ("IMP", "IMP"),
                    ("TST", "TST"),
                    ("V&V", "V&V"),
                    ("DEP", "DEP"),
                    ("CI", "CI"),
                    ("PRC", "PRC"),
                    ("PPL", "PPL"),
                    ("CCM", "CCM"),
                    ("RSK", "RSK"),
                ],
                default="PM",
                max_length=3,
            ),
        ),
    ]
