# Generated by Django 4.1.2 on 2022-11-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_test_tags_test_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="justification",
            field=models.CharField(default="", max_length=500),
        ),
    ]
