# Generated by Django 4.1.2 on 2022-11-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_question_num_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='justification',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tag'),
        ),
    ]
