# Generated by Django 4.1.2 on 2022-11-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_option_justification"),
        ("api", "0015_rename_tags_question_tag"),
    ]

    operations = []
