# Generated by Django 4.1.2 on 2022-11-18 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_merge_20221117_2212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.tag"
            ),
        ),
    ]
