# Generated by Django 4.1.2 on 2022-11-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_solvedtest_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="solvedtest",
            name="grade",
            field=models.IntegerField(default=0),
        ),
    ]
